# fly.toml app configuration file generated for kiisukas-v-2 on 2024-03-20T00:31:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kiisukas-v-2'

[build]

[deploy]
  strategy = "immediate"



[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
