app = "kiisukas-v-2"
primary_region = "ams"

[build]
  builder = "heroku/builder:22"

[deploy]
  strategy = "immediate"

[mounts]
  source = "bot_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1